language: node_js
node_js:
- 6
before_install:
- npm i -g npm@version-number
install:
- npm install
before_script:
- npm install -g gulp-cli
script:
- npm build
cache:
  directories:
  - node_modules
deploy:
- provider: s3
  access_key_id: AKIAIQEUERT6BHRTC26Q
  secret_access_key: &1
    secure: DZBb4s8UqtZhUZ11qktKXTFCFAU3UyDWvbQzVEfg6yOqbfigTKf99MXqxkd+b9ezOnVv46Dh0IbeqY8vui7xaHPGQy9dhkld9zJZTh30D73r59IfupBCOIwG26tSXEvEhciwZX9e++zSJNKOwHvhvcj8BMuflyNGBe5FOhQ1SB0fbx7krxM1odW3KYmgFURbZQPVolOAz7q2d8VWEcrIG9MSnNns9YyHHJ5xFNmMrNZRFfbmcOmwUr1Xyh4YQm6XPhZhDFS5/kg3NqEFIxbgnDVr+IMY1LddjrFZRL5fhDW7bRY9gknWqQDDwzLaAr1+ZOJ2eNNHmyLxn81hMj1/pOn9VWuTul2iOolBcHyICcWZytjjoJqDYXGZVATU7gDqhCQkDfa20klz0YHx7c03TxmRmd1dFR+vri9g0AZbEugsDA4+6nVarFb+esTtaEghFT5OX6kA1VXUoJcqSRH5m8C7l0/qpRM4ZN/paObxpL2iG3juFBUmSdINnQ9Zf1M0IfBSrEuTBhYaqPhEHrL07oZNq3fL2intkWETeojsRHs9/J89dwYnhIU9Y1hUnsqhUDQeWh5WntWh0lfUz5LKSONBpdpvNE3MDDRhSzCx7CJhX1cxu5n5Wq7v8r0K4/ab/p6JmzoYqTcjbXq4qHQ+HiRjJol11d0DbZvyW5APX3E=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: devtanc/car-info-tracker
  bucket: aws-codestar-us-west-2-082659734858-devtanc-demos-pipe
  upload_dir: "/travis"
  revision_type: github
- provider: codedeploy
  access_key_id: AKIAIQEUERT6BHRTC26Q
  secret_access_key: *1
  bucket: aws-codestar-us-west-2-082659734858-devtanc-demos-pipe
  key: "/travis/app.zip"
  bundle_type: zip
  application: devtanc-demos
  deployment_group: devtanc-demos-deploy
  on: *2
before_deploy:
- mkdir -p dpl_cd_upload
- mv app.zip dpl_cd_upload/app.zip
